service: ui
runtime: python37

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
    secure: always
